# Generated by Django 4.1.1 on 2022-10-02 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_usuario_rename_ordenpedido_pedidoproducto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField()),
                ('ubicacion', models.TextField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ubicacion',
            field=models.TextField(max_length=100),
        ),
    ]
